---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: manualtest-codegenllamacpp-nov5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: manualtest-codegenllamacpp-nov5 
  name: manualtest-codegenllamacpp-nov5
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi